//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishesApplication
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }

		public string LogotipSourse
		{
			get
			{
				string imgProductsSrc = $"{ProductPhoto}";
				string allImgSrc = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, imgProductsSrc);

				if (!File.Exists(allImgSrc))
					allImgSrc = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "imgProducts\\picture.png");

				return allImgSrc;
			}
		}


		public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategoryId { get; set; }
        public string ProductPhoto { get; set; }
        public int ManufacturerId { get; set; }
        public int ProviderId { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<decimal> ProductDiscountAmount { get; set; }
        public Nullable<decimal> MaxDiscount { get; set; }
        public Nullable<decimal> CurrentDiscount { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
    
        public virtual CategoryProducts CategoryProducts { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
